name: Manaully Triggered Workflow
on:
    workflow_dispatch:

jobs:
    log-info:
        runs-on: ubuntu-latest
        steps:
            - name: Log Information
              run: |
                  echo "This workflow was triggered manually."
                  echo "Current date and time:"
                  date
                  echo "Listing files in the current directory:"
                  ls -la
                  echo ${GITHUB_REF}
                  echo ${GITHUB_SHA}
                  echo ${GITHUB_REPOSITORY}
                  echo ${GITHUB_ACTOR}
                  echo ${GITHUB_WORKFLOW}
                  echo ${GITHUB_RUN_ID}
                  echo ${GITHUB_RUN_NUMBER}
                  echo ${GITHUB_JOB}
                  echo ${GITHUB_EVENT_NAME}
                  echo ${GITHUB_EVENT_PATH}
                  echo ${GITHUB_WORKSPACE}
                  echo ${GITHUB_ACTION}
                  echo ${GITHUB_ACTIONS}
                  echo ${GITHUB_HEAD_REF}
                  echo ${GITHUB_BASE_REF}
                  echo ${GITHUB_SERVER_URL}
                  echo ${GITHUB_API_URL}
